
name: Build

on:
   push
jobs:
   check-and-publish:
       name: "task-donson-build"
       runs-on: ubuntu-latest
       steps:
            - name: "Checkout source code"
              uses: actions/checkout@v2
            - name: "Setup Node.js"
              uses: actions/setup-node@v1
              with: 
                  node-version: 16
                  registry-url: https://www.npmjs.com/org/

            - name: "Edit config"
              run: git config --global user.name "daniil.nyashka@gmail.com" && git config --global user.name "Daniel"
            - name: "Telegram Notification"
              uses: "appleboy/telegram-action@master"
              with: 
                to: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                args: A new task upload to the repository has been detected. Below is a link to switch to the repository:"https://github.com/DanielPobarzin/Task"


          
